name: Generate PDF Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        name: generate doc
        with:
          scheme: full
          run: |
            apk add ghostscript imagemagick gnupg
            sed -i "s|<policy domain=\"coder\" rights=\"none\" pattern=\"PDF\" />|<policy domain=\"coder\" rights=\"read\|write\" pattern=\"PDF\" />|g" /etc/ImageMagick-*/policy.xml
            cd docs
            mkdir pdf
            PPEDT_LANG=chs l3build doc
            mv doc.pdf pdf/doc_chs.pdf
            l3build doc
            mv doc.pdf pdf/doc.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/pdf
          external_repository: LogCreative/PGFPlotsEdt-doc
          publish_branch: main
          keep_files: true
